# Generated by Django 6.0.4 on 2026-04-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninggoal',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='是否完成'),
        ),
    ]
