# Generated by Django 6.0.4 on 2026-04-10 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_learninggoal_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learninggoal',
            name='is_completed',
        ),
        migrations.AlterField(
            model_name='learninggoal',
            name='description',
            field=models.TextField(blank=True, verbose_name='目标详述'),
        ),
        migrations.AlterField(
            model_name='learninggoal',
            name='title',
            field=models.CharField(max_length=200, verbose_name='大目标名称'),
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='goals.learninggoal')),
            ],
        ),
    ]
