# Generated by Django 6.0.4 on 2026-04-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_remove_learninggoal_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learninggoal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learninggoal',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
