# Generated by Django 6.0.4 on 2026-04-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_alter_learninggoal_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninggoal',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='priority',
            field=models.CharField(choices=[('L', '低'), ('M', '中'), ('H', '高')], default='M', max_length=1),
        ),
    ]
