# Generated by Django 6.0.4 on 2026-04-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_learninggoal_deadline_learninggoal_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
