# Generated by Django 6.0.4 on 2026-04-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_subtask_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learninggoal',
            options={'verbose_name': '学习目标', 'verbose_name_plural': '学习目标'},
        ),
        migrations.AlterModelOptions(
            name='subtask',
            options={'verbose_name': '子任务', 'verbose_name_plural': '子任务'},
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='是否归档'),
        ),
        migrations.AlterField(
            model_name='learninggoal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='learninggoal',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='截止日期'),
        ),
        migrations.AlterField(
            model_name='learninggoal',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='目标描述'),
        ),
        migrations.AlterField(
            model_name='learninggoal',
            name='priority',
            field=models.CharField(choices=[('L', '低'), ('M', '中'), ('H', '高')], default='M', max_length=1, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='learninggoal',
            name='title',
            field=models.CharField(max_length=200, verbose_name='目标标题'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='是否完成'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(max_length=200, verbose_name='任务内容'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
