# Generated by Django 6.0.4 on 2026-04-11 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_alter_learninggoal_options_alter_subtask_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='标签名')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '分类标签',
                'verbose_name_plural': '分类标签',
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='goals', to='goals.tag', verbose_name='分类标签'),
        ),
    ]
