# Generated by Django 6.0.4 on 2026-04-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_tag_learninggoal_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, default='#e3e2e0', max_length=20, null=True, verbose_name='标签颜色'),
        ),
    ]
