# Generated by Django 6.0.4 on 2026-04-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninggoal',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='是否达成'),
        ),
    ]
