# Generated by Django 6.0.4 on 2026-04-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0010_learninggoal_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninggoal',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='归档时间'),
        ),
    ]
