# Generated by Django 6.0.4 on 2026-05-17 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0011_learninggoal_archived_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPathNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_name', models.CharField(default='Python高阶工程路径', max_length=100, verbose_name='自定义路径大类')),
                ('milestone_name', models.CharField(max_length=100, verbose_name='自拟里程碑节点')),
                ('order_index', models.IntegerField(default=0, verbose_name='排序权重')),
                ('linked_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goals.learninggoal', verbose_name='绑定的归档目标')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '自拟定路径节点',
                'verbose_name_plural': '自拟定路径节点',
                'ordering': ['order_index'],
            },
        ),
    ]
